[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd services/mcp-server && python portfolio_mcp_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.9"
PORT = "8000"
